import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "portfolio.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
